Review request: Designing Courses and Writing section updates
RedHatTraining/curriculum-onboarding pull request #25
Opened 2021-01-08 04:30 UTC by dsacco15

## Description

Updated Designing Courses sections and added a Writing Effectively section

@RedHatTraining/content-services please review and add feedback to this PR. See the HTML link below (scroll down) to see the changes in context.

2021-01-08 04:31 UTC, redhat-training-curriculum commented
HTML Built Successfully, preview [here](http://jenkins.prod.nextcle.com/job/RHT/job/curriculum-onboarding/job/PR-25/1/Onboarding_20Documentation_20HTML)

2021-01-08 11:38 UTC, daobrien requested changes
A few fixes needed.

2021-01-08 11:38 UTC, daobrien commented on content/upskilling/02.adoc
> +**Phase I (MVP)** is just Guided Exercises or End-of-chapter Labs and Open content with light or no narrative. The idea is to create an MVP to gather feedback from customers, internal partners, and s
Make *Phase I (MVP)* a heading.
```suggestion
==== Phase I (MVP)
This phase includes guided exercises and end-of-chapter labs and "OPEN" content with light or no narrative. The idea is to create an MVP to gather feedback from customers, internal partners, and stakeholders. Content Services is not required to review anything at this point but provides assistance, as needed. The exercises in this phase can be developed with minimal step instructions but typically will include grading scripts.
```
afaik MVP doesn't include grading scripts.

2021-01-08 11:38 UTC, daobrien commented on content/upskilling/02.adoc
> +**Phase II (General Availability)** is when chapter content, including narrative and labs, is built out fully to be ready for release. Where Phase I content is minimal, this phase is where everything
```suggestion
==== Phase II (General Availability)
This phase is when the balance of the content, including narrative and labs, is fully developed and reviewed ready for release. Where Phase I content is minimal, this phase is where everything is fleshed out so the learner has all the information needed to be successful in the course.
```

2021-01-08 11:38 UTC, daobrien commented on content/upskilling/02.adoc
> +
Phase III? I know there is no design meeting for this phase but we should let them know that it exists.

2021-01-08 11:38 UTC, daobrien commented on content/upskilling/02.adoc
> +=== Design Meetings in Phases
Design meetings are not held in phases. Perhaps you want something like "Design Meeting Opportunities" or "Scheduling Design Meetings" or similar?

2021-01-08 11:38 UTC, daobrien commented on content/upskilling/02.adoc
> +They break down in the following manner.
```suggestion
Design meetings are scheduled at two junctures: The first is held before Phase I begins and the second before Phase II begins. The agenda of each is described below.
```

2021-01-08 11:38 UTC, daobrien commented on content/upskilling/02.adoc
> +The ID, Curriculum Architect, and development team meet to discuss the approach to creating the Guided Exercises and/or Labs.
```suggestion
This meeting addresses how to approach creating the guided exercises and labs.
```

2021-01-08 11:38 UTC, daobrien commented on content/upskilling/02.adoc
> +Using the course outline, which may be in one of these formats, Detailed Course Outline or Timing document, listing the chapters, sections, and exercise titles, we review the following
```suggestion
This meeting uses the Detailed Course Outline (DCO) to review the following topics:
```
I **know** the "DCO" comes in a variety of formats but I think it's pointless to list all the different guises under which it may appear. If we just say DCO then ppl get the idea.

2021-01-08 11:38 UTC, daobrien commented on content/upskilling/02.adoc
> +Which GE’s cannot be developed due to classroom environment constraints or issues?
Don't write "GE's" or "CA's" or whatever when you're talking about plurals.

2021-01-08 11:38 UTC, daobrien commented on content/upskilling/02.adoc
> +Which GE’s cannot be developed due to classroom environment constraints or issues?
```suggestion
Which GEs cannot be developed due to classroom issues?
```

2021-01-08 11:38 UTC, daobrien commented on content/upskilling/02.adoc
> +All the same players from Phase I meet but the objective of this design meeting is to define design for each chapter in multiple, shorter, focused meetings, focusing on the following
```suggestion
The objective of this meeting is to define the design of each chapter in multiple, shorter, focused meetings, focusing on the following:
```
I'm not sure that this makes sense. The phase 2 design meeting is actually a series of shorter meetings? If so, you need to spell that out better.

2021-01-08 11:38 UTC, daobrien commented on content/upskilling/02.adoc
> +Content flow from chapter-to-chapter - based on the course outline, do the topics make sense in the order they’re in?
```suggestion
Content flow from chapter to chapter. Based on the course outline, do the topics make sense in their current order?
```

2021-01-08 11:38 UTC, daobrien commented on content/upskilling/02.adoc
> +Ask questions as a team about all aspects of the chapter being reviewed, to give the Architect an opportunity to clarify.
```suggestion
Ask questions as a team about all aspects of the chapter being reviewed, to give the architect an opportunity to clarify.
```

2021-01-08 11:38 UTC, daobrien commented on content/upskilling/02.adoc
> +Make suggestions for modifying content, adding or pulling and
Incomplete sentence.

2021-01-08 11:38 UTC, daobrien commented on content/upskilling/collaborating.adoc
>  This section describes how to effectively collaborate with Content Services and your peers. Review the following documents
Be careful with punctuation. I've noticed lots of missing bits and pieces.

2021-01-08 20:12 UTC, dsacco15 commented on content/upskilling/02.adoc
> +=== When and How do We Conduct a Design Meeting?
I will consider this change. They don't bother me in a less formal environment.

2021-01-08 20:14 UTC, dsacco15 commented on content/upskilling/collaborating.adoc
>  This section describes how to effectively collaborate with Content Services and your peers. Review the following documents
Punctuation is missing, specifically, colons, because they weren't rendering correctly for me in asciidoc. I did some research in the Google but their suggestions didn't seem to work.

2021-01-08 20:15 UTC, dsacco15 commented on content/upskilling/02.adoc
> +  - Curriculum developer
I will update the personas. I tried to do that but obviously missed many. It wasn't a focus for this first run.

2021-01-08 20:17 UTC, dsacco15 reviewed
Some changes were committed in this review but others still need to be implemented.

2021-01-08 21:11 UTC, dsacco15 commented on content/upskilling/02.adoc
> +
Updated this section.

2021-01-08 21:13 UTC, dsacco15 commented on content/upskilling/collaborating.adoc
>  This section describes how to effectively collaborate with Content Services and your peers. Review the following documents
I worked it out with the colons. This should read more consistently now.

2021-01-08 21:16 UTC, dsacco15 commented on content/upskilling/02.adoc
> +=== Design Meetings in Phases
Updated.

2021-01-08 21:18 UTC, dsacco15 commented on content/upskilling/02.adoc
> +Using the course outline, which may be in one of these formats, Detailed Course Outline or Timing document, listing the chapters, sections, and exercise titles, we review the following
Updated.

2021-01-08 21:20 UTC, dsacco15 reviewed
I updated the issues.

2021-01-08 21:46 UTC, dsacco15 reviewed
Resolved issues.

2021-01-08 22:01 UTC, dsacco15 commented
@daobrien I made the changes, committed, and pushed them but I am still in need of one change but I thought I completed all
. Can you take a look on Monday?

2021-01-12 00:19 UTC, daobrien reviewed
I guess the entire site is draft atm so in the interests of getting it "out there" how about we just merge this and fix smaller chunks? What was that about writing modularly? Remember that titles require title case, spelling and punctuation is important, as is consistency. Avoid titles in the form of questions.

2021-01-12 15:35 UTC, richardallred approved these changes
Approving this PR so that it can be merged for now, sounds like @daobrien is okay with that, he's just probably sleeping at the moment.

2021-01-12 15:48 UTC, merged